### ISSUE TITLE
When writing many-to-many, cannot create child with ->1 link to same entity being written to

### ISSUE THREAD

**Issue by amoe** [friemen/aggregate#8]
Hi, this is similar to #7 except that the `company` entity is removed and instead author has a `->1` link back to the `book`.  So there is both a many-to-many relation between book and author, and a many-to-one relationship between each author and a book.  (I know that the data model for this example now makes absolutely no sense.)

```
(def db-host "localhost")
(def db-port 5432)
(def db-name "test")
(def db-spec {:classname "org.postgresql.Driver"
      :subprotocol "postgresql"
      :subname (str "//" db-host ":" db-port "/" db-name)})

(def model
  (agg/make-er-config
   (agg/entity :book
               (agg/->mn :authors :author {:query-fn
                                           (agg/make-query-<many>-fn :author
                                                                     :author_books    ; link table
                                                                     :book_id
                                                                     :author_id)
                                           :update-links-fn 
                                           (agg/make-update-links-fn :author_books    ; link table
                                                                     :book_id
                                                                     :author_id)}))
   (agg/entity :author
               (agg/->1 :book :book {:fk-kw :book_id
                                           :owned? true    ;; ??
                                           }))))


(def ddl
  ["DROP TABLE IF EXISTS book, author, author_books"
   "CREATE TABLE book (id SERIAL PRIMARY KEY, book_name VARCHAR(80));"
   "CREATE TABLE author (id SERIAL PRIMARY KEY, author_name VARCHAR(80), book_id INTEGER NOT NULL REFERENCES book (id));"
   "CREATE TABLE author_books (author_id INTEGER NOT NULL REFERENCES author (id), book_id INTEGER NOT NULL REFERENCES book (id))"])

(declare attempt-save)

(defn setup-prerequisites []
  (doseq [t ddl]
    (jdbc/execute! db-spec [t]))

  (let [book-id (-> (agg/save! model db-spec :book {:book_name "The Great Gatsby" :authors []}) :id)]
    (attempt-save book-id)))


(defn attempt-save [book-id]
    (agg/save! model db-spec :book
               {:book_name "Moby Dick"
                :authors [{:author_name "Herman Melville" :book {:id book-id}}]
                :id book-id})
    (println "Hello, World!"))
```

Using the same syntax as before, I indicate that the record was already created using the form `:book {:id book-id}`.  However, aggregate does not insert the row properly and I get an error `null value in column "book_id" violates not-null constraint`.  Aggregate is eliding the book ID altogether and attempting to `INSERT INTO author ( author_name ) VALUES ( ... )`.  If I use the syntax `:book_id book-id` instead, this example works, but it seems that this syntax is incorrect by the spec.

**Comment by friemen** [comment]
When load and save! functions follow the relations in the er-config model they remove entity configurations from the model that were already visited. They do this to prevent possibly infinite recursions. Therefore the entry `:book {:id book-id}` is not recognized by save! because a :book entity was processed on the 1st level of the call to save!. 

At the moment I'm not sure if this limitation is reasonable. I'll have to dig a bit deeper to find out if there is another way to prevent infinite recursions.

**Comment by friemen** [comment]
aggregate 1.1.3 will save recursive structures like

```
{:book_name "Moby Dick"
 :authors [{:author_name "Herman Melville" :book {:id book-id}}]
 :id book-id}
```

now as one expects.

Note, that if you load this book, you'll get a data structure like

```
{:id 1,
 :book_name "Moby Dick",
 :aggregate.core/entity :book,
 :authors
 [{:id 1,
   :author_name "Herman Melville",
   :company_id nil,
   :book_id_2 1,
   :aggregate.core/entity :author}]}
```

because the foreign-key `book_id` appears twice in the join of tables author and author_books.
As you've pointed out above, the DB schema in this case is not what one would actually use in a real world project.
